# Generated by Django 3.2.25 on 2025-06-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='暱稱（可留空）')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
    ]
