# Generated by Django 3.2.25 on 2025-06-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_message_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashtag',
            field=models.CharField(choices=[('ticketing', '購票'), ('pickup', '取票'), ('account', '會員相關'), ('else', '其他')], default='ticketing', max_length=20, verbose_name='類別'),
        ),
    ]
