# Generated by Django 3.2.25 on 2025-06-16 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名稱')),
                ('description', models.TextField(verbose_name='描述')),
                ('main_image', models.ImageField(upload_to='events/', verbose_name='主視覺圖')),
                ('event_date', models.DateTimeField(verbose_name='演出日期')),
                ('location', models.CharField(max_length=200, verbose_name='地點')),
                ('organizer', models.CharField(max_length=200, verbose_name='主辦單位')),
                ('seating_map', models.ImageField(blank=True, null=True, upload_to='events/seating_maps/', verbose_name='座位圖')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='票種名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='票價')),
                ('quantity', models.PositiveIntegerField(verbose_name='座位數')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='已售張數')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.event')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='張數')),
                ('status', models.CharField(choices=[('pending', '未結帳'), ('paid', '已結帳'), ('collected', '已取票'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
