# Generated by Django 3.2.25 on 2025-06-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(default='static/image/default.png', upload_to='events/', verbose_name='主視覺圖'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seating_map',
            field=models.ImageField(blank=True, default='static/image/default_seat.png', null=True, upload_to='events/seating_maps/', verbose_name='座位圖'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='座位數'),
        ),
    ]
