# Generated by Django 3.2.25 on 2025-06-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20250617_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(default='event/default.png', upload_to='media/events/', verbose_name='主視覺圖'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seating_map',
            field=models.ImageField(blank=True, default='event/seating_maps/default_seat.png', null=True, upload_to='media/events/seating_maps/', verbose_name='座位圖'),
        ),
    ]
