# Generated by Django 3.2.25 on 2025-06-16 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20250617_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開賣時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(default='event/default.png', upload_to='events/', verbose_name='主視覺圖'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seating_map',
            field=models.ImageField(blank=True, null=True, upload_to='events/seating_maps/', verbose_name='座位圖'),
        ),
    ]
