# Generated by Django 3.2.25 on 2025-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20250618_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(default='events/default.png', upload_to='events/', verbose_name='主視覺圖'),
        ),
    ]
